version: "2.2"
  
volumes:
  elasticsearch-data:
    driver: local
  
services:
  elasticsearch:
    image: elastic/elasticsearch:6.8.8
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200